server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://121.4.53.107:3306/springboot_test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Admin_46xx
  application:
    name: user-service

#  别名包扫描
mybatis:
  type-aliases-package: cn.ylj.user.entity

#  注册成为客户端
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ## 注册为ip而不是用服务名
    prefer-ip-address: true
    ip-address: 127.0.0.1
    ## 服务续约时间和服务时效剔除时间（秒）, 30s续约一次表示服务还活着，90s了还没有续约就从中心剔除掉。证明死了
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
