server:
  port: ${port:9090}
spring:
  application:
    name: consumer


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

# 配置Hystrix 降级阈值时间 默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000