server:
  port: 10010

# 该工程名是对外的单一的名称
spring:
  application:
    name: api-gateway

# 网关路由表
  cloud:
    gateway:
      routes:
        - id: user-service-route        #路由项id
#          uri: http://127.0.0.1:9092   #静态路由
          uri: lb:http://user-service   #动态路由，从注册中心获取路由信息
          predicates:                   #断言为true的，路由转发到uri
            - Path=/user/**

# eureka 客户端配置
eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  # 服务间调用 使用ip，而不是使用服务名
  instance:
    prefer-ip-address: true