server:
  port: 10010

# 该工程名是对外的单一的名称
spring:
  application:
    name: api-gateway

# 网关路由表
  cloud:
    gateway:
      routes:
        - id: user-service-route2       #路由项id2
          uri: lb:http://user-service   #动态路由，从注册中心获取路由信息，且loadbalance
          predicates:                   #断言为true的，路由转发到uri
            - Path=/api/**
          filters:
            - StripPrefix=1             #1表示剥离路径中第一级/api
                                        #剥离 外部请求http://127.0.0.1:10010/api/user/8-->网关处理成http://127.0.0.1:10010/user/8 -->微服务集群
            - MyParam=name              #自定义过滤器的参数，自定义过滤器会在Filter chain中执行，MyParam是固定写法
                                        #效果 http://127.0.0.1:10010/api/user/2?name=yanglujian --> 获取到name的值

        - id: user-service-route        #路由项id
#          uri: http://127.0.0.1:9092   #静态路由
          uri: lb:http://user-service   #动态路由，从注册中心获取路由信息，且loadbalance
          predicates:                   #断言为true的，路由转发到uri
#            - Path=/user/**
            - Path=/**
          filters:
            - PrefixPath=/user          #前缀 外部请求http://127.0.0.1:10010/8-->网关处理成http://127.0.0.1:10010/user/8 -->微服务集群

      ## 对所有的请求都执行,gw中有许多的过滤器可以配置
      default-filters:
        - AddResponseHeader=X-Response-Foo, Bar   #对响应体添加统一的响应头:值
        - AddResponseHeader=ylj, hahaha   #对响应体添加统一的响应头
# eureka 客户端配置
eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  # 服务间调用 使用ip，而不是使用服务名
  instance:
    prefer-ip-address: true